### ISSUE TITLE
Error while running the axample app

### ISSUE THREAD

**Issue by dheerajbred** [reedom/flutter_appnext#1]
This exception was thrown when the example app was compiled

```
` [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method banner.init on channel com.reedom.flutter_appnext)
E/flutter ( 2059): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 2059): <asynchronous suspension>
E/flutter ( 2059): #1      new ANBannerAd (package:flutter_appnext/src/banner_ad.dart:57:13)
E/flutter ( 2059): #2      _BannerAdScreenState.initState (package:flutter_appnext_example/screens/banner_screen.dart:29:17)
E/flutter ( 2059): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3845:58)
E/flutter ( 2059): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter ( 2059): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter ( 2059): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter ( 2059): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter ( 2059): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter ( 2059): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter ( 2059): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter ( 2059): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter ( 2059): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter ( 2059): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter ( 2059): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter ( 2059): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter ( 2059): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter ( 2059): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
E/flutter ( 2059): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter ( 2059): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter ( 2059): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter ( 2059): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter ( 2059): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter ( 2059): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter ( 2059): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter ( 2059): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter ( 2059): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter ( 2059): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter ( 2059): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:386
I/flutter ( 2059): ══╡ EXCEPTION CAUGHT BY STREAMS_CHANNEL ╞═══════════════════════════════════════════════════════════
I/flutter ( 2059): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter ( 2059): com.reedom.flutter_appnext/event:
I/flutter ( 2059): MissingPluginException(No implementation found for method listen#1 on channel
I/flutter ( 2059): com.reedom.flutter_appnext/event)
I/flutter ( 2059): When the exception was thrown, this was the stack:
I/flutter ( 2059): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
I/flutter ( 2059): <asynchronous suspension>
I/flutter ( 2059): #1      StreamsChannel.receiveBroadcastStream.<anonymous closure> (package:streams_channel/streams_channel.dart:40:29)
I/flutter ( 2059): <asynchronous suspension>
I/flutter ( 2059): #6      new ANBannerAd (package:flutter_appnext/src/banner_ad.dart:58:46)
I/flutter ( 2059): #7      _BannerAdScreenState.initState (package:flutter_appnext_example/screens/banner_screen.dart:29:17)
I/flutter ( 2059): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3845:58)
I/flutter ( 2059): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
I/flutter ( 2059): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
I/flutter ( 2059): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
I/flutter ( 2059): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
I/flutter ( 2059): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
I/flutter ( 2059): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 2059): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
I/flutter ( 2059): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
I/flutter ( 2059): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
I/flutter ( 2059): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
I/flutter ( 2059): #101    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4658:32)
I/flutter ( 2059): #102    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4991:17)
I/flutter ( 2059): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #104    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:16)
I/flutter ( 2059): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3893:5)
I/flutter ( 2059): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #112    ProxyElement.update (package:flutter/src/widgets/framework.dart:4005:5)
I/flutter ( 2059): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4882:14)
I/flutter ( 2059): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3893:5)
I/flutter ( 2059): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4882:14)
I/flutter ( 2059): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4882:14)
I/flutter ( 2059): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2746:15)
I/flutter ( 2059): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
I/flutter ( 2059): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
I/flutter ( 2059): #126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2271:33)
I/flutter ( 2059): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 2059): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter ( 2059): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1008:15)
I/flutter ( 2059): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:948:9)
I/flutter ( 2059): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:860:5)
I/flutter ( 2059): #135    _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 2059): #136    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 2059): (elided 7 frames from package dart:async)
I/flutter ( 2059): ════════════════════════════════════════════════════════════════════════════════════════════════════`
```

**Comment by reedom** [comment]
Did you test on Android?
This plugin supports iOS only.

**Comment by dheerajbred** [comment]
ooops! I didn't see that. Thanks anyways
